# Generated by Django 3.1.7 on 2021-03-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('company', models.CharField(default='Null', max_length=100)),
                ('country', models.CharField(default='Null', max_length=100)),
                ('address', models.CharField(default='Null', max_length=100)),
                ('reg_no', models.CharField(default='Null', max_length=100)),
                ('employees', models.CharField(default='Null', max_length=100)),
                ('sector', models.CharField(default='Null', max_length=100)),
                ('turnover', models.CharField(default='Null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_renewable', models.CharField(default='Null', max_length=100)),
                ('electricity_amount', models.CharField(default='Null', max_length=100)),
                ('electricity_provider', models.CharField(default='Null', max_length=100)),
                ('electricity_type', models.CharField(default='Null', max_length=100)),
                ('electricity_heating', models.CharField(default='Null', max_length=100)),
                ('electricity_gas', models.CharField(default='Null', max_length=100)),
                ('travel_air_travel', models.CharField(default='Null', max_length=100)),
                ('travel_automobile_mileage', models.CharField(default='Null', max_length=100)),
                ('travel_automobile_commute', models.CharField(default='Null', max_length=100)),
                ('travel_bus', models.CharField(default='Null', max_length=100)),
                ('travel_coach', models.CharField(default='Null', max_length=100)),
                ('travel_train', models.CharField(default='Null', max_length=100)),
                ('travel_int_train', models.CharField(default='Null', max_length=100)),
                ('travel_subway', models.CharField(default='Null', max_length=100)),
                ('travel_tram', models.CharField(default='Null', max_length=100)),
                ('travel_taxi', models.CharField(default='Null', max_length=100)),
                ('travel_accommodation_hotel', models.CharField(default='Null', max_length=100)),
                ('travel_accommodation_motel', models.CharField(default='Null', max_length=100)),
                ('travel_accommodation_airbnb', models.CharField(default='Null', max_length=100)),
                ('travel_accommodation_hostel', models.CharField(default='Null', max_length=100)),
                ('office_utilities_desktop', models.CharField(default='Null', max_length=100)),
                ('office_utilities_laptop', models.CharField(default='Null', max_length=100)),
                ('office_waste_bio', models.CharField(default='Null', max_length=100)),
                ('office_waste_battery', models.CharField(default='Null', max_length=100)),
                ('office_waste_plastic', models.CharField(default='Null', max_length=100)),
                ('office_waste_glass', models.CharField(default='Null', max_length=100)),
                ('office_waste_paper', models.CharField(default='Null', max_length=100)),
                ('office_waste_hardware', models.CharField(default='Null', max_length=100)),
                ('office_water', models.CharField(default='Null', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.registrationdata')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
