# Generated by Django 3.1.7 on 2021-04-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_carbondata_registrationdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbondata',
            old_name='office_waste_battery',
            new_name='office_waste_general',
        ),
        migrations.RenameField(
            model_name='carbondata',
            old_name='office_waste_glass',
            new_name='travel_air_travel_long',
        ),
        migrations.RenameField(
            model_name='carbondata',
            old_name='office_waste_hardware',
            new_name='travel_air_travel_short',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_waste_paper',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='office_waste_plastic',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_accommodation_hostel',
        ),
        migrations.RemoveField(
            model_name='carbondata',
            name='travel_air_travel',
        ),
    ]
