# Generated by Django 3.1.7 on 2021-07-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(default='Null', max_length=100)),
                ('authorizer', models.CharField(default='Null', max_length=100)),
                ('bank_name', models.CharField(default='Null', max_length=100)),
                ('account_number', models.CharField(default='Null', max_length=100)),
                ('amount', models.IntegerField(default='Null', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
