# Generated by Django 3.1.7 on 2021-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210716_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='amount',
            field=models.IntegerField(default='Null'),
        ),
    ]
