# Generated by Django 3.1.7 on 2021-07-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210720_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.registrationdata'),
            preserve_default=False,
        ),
    ]
